import mysql.connector

dbase = mysql.connector.connect(host="127.0.0.1", user="umbreone", password="dYZ7g75WMAJ8CQPO", database="umbreone")
dbcs = dbase.cursor(dictionary=True)
dbcs.execute("SELECT * FROM `files` ORDER BY `Internal_ID` DESC;")
ls = dbcs.fetchall()
for i in ls:
    intid = "internal_id:" + str(i["Internal_ID"])
    fileext = "file_ext:" + str(i["File_EXT"])
    displayname = "display_name:" + str(i["Display_Name"])
    rating = "rating:" + str(i["Rating"])
    artist = "artist:" + str(i["Artist"])
    flat = "flat:" + str(i["Flat"])
    upload_datetime = "upload_datetime:" + str(i["Upload_Datetime"])
    print(intid)
    print(fileext)
    print(displayname)
    print(rating)
    print(artist)
    print(flat)
    print(upload_datetime)
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], intid, "Internal_ID"))
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], fileext, "File_EXT"))
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], displayname, "Display_Name"))
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], rating, "Rating"))
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], artist, "Artist"))
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], flat, "Flat"))
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s);", (i["Internal_ID"], upload_datetime, "Upload_Datetime"))
dbcs.execute("SELECT * FROM `tags` ORDER BY `Tag_ID` DESC;")
tagls = dbcs.fetchall()
for i in tagls:
    dbcs.execute("INSERT INTO `tag_search` (`File_ID`, `Tag_ID`, `Tag`, `Tag_Type`) VALUES (%s, %s, %s, %s);", (i["File_ID"], i["Tag_ID"], str(i["Tag"]), "Tag"))
dbase.commit()
dbcs.close()
dbase.close()